=== babayoshihiko/website/xml/finkfaq.dtd
<!ELEMENT answer ( codeblock | p | ul )* >

<!ELEMENT chapter ( title, shorttitle, faqentry+ ) >
<!ATTLIST chapter filename NMTOKEN #REQUIRED >

<!ELEMENT code ( #PCDATA | em )* >

<!ELEMENT codeblock ( #PCDATA ) >

<!ELEMENT cvsid ( #PCDATA ) >

<!ELEMENT document ( title, shorttitle, cvsid, preface, chapter+ ) >
<!ATTLIST document filename NMTOKEN #REQUIRED >

<!ELEMENT em ( #PCDATA ) >

<!ELEMENT faqentry ( question, answer ) >
<!ATTLIST faqentry name ID #REQUIRED >

<!ELEMENT filename ( #PCDATA ) >

<!ELEMENT li ( #PCDATA | code | codeblock | p )* >

<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link url CDATA #REQUIRED >

<!ELEMENT literal ( #PCDATA ) >

<!ELEMENT p ( #PCDATA | code | codeblock | em | filename | link | literal )* >

<!ELEMENT preface ( p+ ) >

<!ELEMENT question ( p ) >

<!ELEMENT shorttitle ( #PCDATA ) >

<!ELEMENT title ( #PCDATA ) >

<!ELEMENT ul ( li+ ) >

=== babayoshihiko/website/xml/faq/faq.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../finkfaq.dtd">
<document filename="index" lang="en">
  <title>The Fink F.A.Q.</title>
  <shorttitle>F.A.Q.</shorttitle>
  <cvsid>$Id: faq.en.xml,v 1.69 2006/06/09 14:57:47 dmrrsn Exp $</cvsid>
  <preface>
    <p>This is the list of frequently asked questions about Fink. Like in most FAQs, some questions are taken from real life and some are made up. It's really more like a documentation written in an ad-hoc, question and answer style.</p>
    <p>The FAQ consists of several pages, one for each section. All questions are listed and linked in the table of contents below.</p>
  </preface>
  <chapter filename="general">
    <title>General Questions</title>
    <shorttitle>General</shorttitle>
    <faqentry name="what">
      <question>
        <p>What is Fink?</p>
      </question>
      <answer>
        <p>Fink wants to bring more Unix software to Mac OS X, which results in two main goals:</p>
        <p>Goal number one is porting software to Mac OS X. That means we take commodity Open Source Unix software and fix whatever is necessary so that it will compile and run on Mac OS X. Sometimes that's easy, but it can also be very hard or even impossible for some packages. We're trying to provide tools and documentation to make this easier.</p>
        <p>Goal number two is making the results available to casual users.  For this, we build a distribution using package management tools ported over from Linux, namely <code>dpkg</code> and <code>apt-get</code>, written by and for the  <link url="http://www.debian.org/">Debian GNU/Linux</link> project. The binary distribution uses the <code>.deb</code> package format. For building packages from source, we have our own tool, named <code>fink</code>, which creates those <code>.deb</code> package files.</p>
      </answer>
    </faqentry>
    <faqentry name="naming">
      <question>
        <p>What does the name Fink stand for?</p>
      </question>
      <answer>
        <p>	Nothing, it's just a name. It's not even an acronym.</p>
        <p>	Well, actually Fink is the German name for Finch, a kind of bird. I was looking for a name for the project, and the name of the OS, Darwin, led me to think about Charles Darwin, the Galapagos Islands and evolution. I remembered a piece about the so-called Darwin Finches and their beaks from school, and well, that's it...</p>
      </answer>
    </faqentry>
    <faqentry name="bsd-ports">
      <question>
        <p>	How is Fink different from the BSD port mechanism (this includes OpenPackages and GNU-Darwin)?
		</p>
      </question>
      <answer>
        <p>	Some main advantages:</p>
        <ul>
          <li>
            <p> It's written in Perl, not make/shell. Thus it  doesn't rely on special features only found in BSD make. There is no need to flag packages that need GNU make to build.</p>
          </li>
          <li>
            <p> dpkg provides sophisticated management for binary packages - smooth updating, special handling for configuration files, virtual packages and other advanced dependencies. </p>
          </li>
          <li>
            <p> Fink doesn't install into /usr/local unless explicitly requested and doesn't require fiddling with /usr/bin/make or other system-provided commands. That makes it safer to use and reduces interference with Mac OS X and third-party packages to a minimum.</p>
          </li>
        </ul>
      </answer>
    </faqentry>
    <faqentry name="usr-local">
      <question>
        <p>Why doesn't Fink install into /usr/local?</p>
      </question>
      <answer>
        <p>	There are several reasons, but the common line is "because breakage will occur".</p>
        <p>	Reason One: Third-party software. /usr/local is the well-established place to put software that is not part of the system shipped by the original vendor. This means that it is a good place to put stuff. However, it also means that other people will put stuff there, too. Most install routines will just overwrite what's there - this also applies to dpkg. One can, of course, choose not to install third-party software in /usr/local. Unfortunately, most installers don't tell you beforehand what they will install where.</p>
        <p>	Reason Two: /usr/local/bin is in the default PATH. This means that your shell will find the installed programs without additional measures. But it also means that you do have to take additional measures if you do not want to use the programs. In extreme cases, this can also affect the system itself - many parts depend on shell scripts.</p>
        <p>	Reason Three: The compiler tool chain searches /usr/local by default. The compiler searches /usr/local/include for header files and the linker searches /usr/local/lib for libraries. Again, this is sometimes a welcome convenience, but it's very hard to disable should the need arise. You can easily disable the compiler by putting a garbage file called <code>stdio.h</code> into /usr/local/include.</p>
        <p>	All that said, it is possible to install Fink into /usr/local. The installation script will warn you explicitly, but proceed once you acknowledge that you're doing this at your own risk.</p>
      </answer>
    </faqentry>
    <faqentry name="why-sw">
      <question>
        <p>Then why did you choose /sw?</p>
      </question>
      <answer>
        <p> That choice is quite arbitrary, but is likely to stay for the foreseeable future for practical (upgrade) issues as well as the fact that it's safe from conflicting with other packaging systems.</p>
      </answer>
    </faqentry>
  </chapter>
  <chapter filename="relations">
    <title>Relations with Other Projects</title>
    <shorttitle>Relations</shorttitle>
    <faqentry name="upstream">
      <question>
        <p>Do you contribute your patches back to the upstream maintainers?</p>
      </question>
      <answer>
        <p>We're trying to. Sometimes sending patches back is easy and  everyone is happy once the next release of the package is out. Unfortunately with most packages it's not that easy. Some common problems:</p>
        <ul>
          <li>The Fink package maintainer is very busy and doesn't have the time to send the patch and accompanying explanations to the upstream
          maintainers.</li>
          <li>The upstream maintainers reject the patch. There are lots of valid reasons for this. Most upstream maintainers have a strong interest in clean code, clean configure checks, and compatibility with other platforms.</li>
          <li>The upstream maintainers accept the patch, but it takes some weeks or months until they release a new version of their package.</li>
          <li>The package has been abandoned by the original authors and there will be no new releases into which the patch could be merged.</li>
        </ul>
      </answer>
    </faqentry>
    <faqentry name="debian">
      <question>
        <p>What is your relation with the Debian project? Are you porting Debian Linux to Mac OS X?</p>
      </question>
      <answer>
        <p>There is no formal relation between Fink and <link url="http://www.debian.org">Debian</link>. Fink is <em>not</em> a port  of the Debian GNU/Linux distribution. We have ported Debian's package management tools (dpkg, dselect, apt-get) though, and use these tools and the .deb binary package format. The actual packages are tailor-made for Mac OS X / Darwin and don't use the Debian source package  format.</p>
      </answer>
    </faqentry>
    <faqentry name="apple">
      <question>
        <p>What is your relation with Apple?</p>
      </question>
      <answer>
        <p>
          <link url="http://www.apple.com/">Apple</link> is aware of Fink and has given us some support as part of their Open Source relations efforts. In the summer and fall of 2001, they provided us with pre-release seeds of new Mac OS X versions in the hope that Fink packages can be adapted in time for the release. Quote:  <em>"Hopefully it underscores the commitment that many suspect we're not willing to provide. We'll get better at the open source game over time."</em> Thanks Apple!</p>
      </answer>
    </faqentry>
    <faqentry name="darwinports">
      <question>
        <p>What is your relation with Darwinports?</p>
      </question>
      <answer>
        <p>Darwinports and Fink are complementary projects. There is some overlap between the two projects, and several people contribute to both the Fink and DarwinPorts projects. For example, Benjamin Reed is doing the KDE packages for both. Darwinports and Fink are free to make use of each other's patches, and we have discussed collaboration on a new dependency engine.</p>
        <p>DarwinPorts started from scratch to try a different approach to a packaging system. Read the statement on <link url="http://darwinports.opendarwin.org/">the DarwinPorts homepage</link>
        for details.</p>
      </answer>
    </faqentry>
  </chapter>
  <chapter filename="mirrors">
    <title>Fink mirrors</title>
    <shorttitle>Mirrors</shorttitle>
    <faqentry name="when-use">
      <question>
        <p>What are Fink Mirrors?</p>
      </question>
      <answer>
        <p>Fink mirrors are rsync servers mirroring the current and stable description files that Fink uses to build packages from source.</p>
      </answer>
    </faqentry>
    <faqentry name="why">
      <question>
        <p>Why should I use rsync mirrors?</p>
      </question>
      <answer>
        <p>Rsync is a very fast protocol. It will update the description files faster than the old CVS update method. Furthermore, CVS updates are  always done from sourceforge.net while rsync updates can be done from a mirror close to you.</p>
      </answer>
    </faqentry>
    <faqentry name="where">
      <question>
        <p>Where can I find more information about Fink mirrors?</p>
      </question>
      <answer>
