=== babayoshihiko/website/xml/finkdoc.dtd
<!-- Root elements -->
<!ELEMENT article ( title, shorttitle, cvsid, preface?, section+ ) >
<!ATTLIST article filename NMTOKEN #REQUIRED >

<!ELEMENT document ( title, shorttitle, cvsid, preface?, chapter+ ) >
<!ATTLIST document filename NMTOKEN #REQUIRED >


<!-- Structure -->
<!ELEMENT chapter ( title, shorttitle, preface?, section+ )* >
<!ATTLIST chapter filename NMTOKEN #REQUIRED >

<!ELEMENT title ( #PCDATA ) >
<!ELEMENT shorttitle ( #PCDATA ) >
<!ELEMENT cvsid ( #PCDATA ) >
<!ELEMENT preface ( p+ ) >

<!ELEMENT section (title?, ( codeblock | itemtable | ol | p | ul )*) >
<!ATTLIST section name NMTOKEN #IMPLIED >


<!-- Block elements -->
<!ELEMENT codeblock ( #PCDATA | em )* >
<!ELEMENT p ( #PCDATA | code | codeblock | em | link | tt | xref )* >


<!-- Inline -->
<!ELEMENT code ( #PCDATA | em )* >
<!ELEMENT em ( #PCDATA ) >
<!ELEMENT tt ( #PCDATA ) >


<!-- Links -->
<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link url CDATA #REQUIRED >

<!ELEMENT xref ( #PCDATA ) >
<!ATTLIST xref chapter NMTOKEN #IMPLIED >
<!ATTLIST xref section NMTOKEN #IMPLIED >


<!-- Lists -->
<!ELEMENT ol ( li+ ) >
<!ELEMENT ul ( li+ ) >
<!ELEMENT li ( #PCDATA | code | codeblock | em | link | p )* >

<!ELEMENT itemtable ( item+ ) >
<!ATTLIST itemtable labeld CDATA "Value" >
<!ATTLIST itemtable labelt CDATA "Field" >

<!ELEMENT item ( itemt, itemd ) >
<!ELEMENT itemt ( #PCDATA | code | em )* >
<!ELEMENT itemd ( codeblock | p | ul )* >

=== babayoshihiko/website/xml/cvsaccess/cvs.es.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">
<article filename="index" lang="es" fsroot="../../">
  <title>Ajustando el Acceso al CVS de Fink</title>
  <shorttitle>Acceso al CVS de Fink</shorttitle>
  <cvsid>$Id: cvs.es.xml,v 1.8 2012/11/11 15:20:13 gecko2 Exp $</cvsid>
  <preface>
    <p>
Fink es desarrollado mediante CVS.
Esto significa que puedes mantenerte al día entre las liberaciones del Fink y siempre tener lo ultimo.
Esta página le explicará como ajustar una instalacion existente de Fink para que se actualice mediante el CVS.
La informacion de esta pagina aplica al Fink 0.3.x y posterior.
</p>
  </preface>
  <section>
    <title>Estructura del CVS de Fink</title>
    <p>Fink posee varios módulos de CVS. El módulo <code>dists</code> (<link url="http://fink.cvs.sourceforge.net/fink/">ViewCVS</link>)
contiene las descripciones de los paquetes y parches para OS 10.2 y posterior. Existen otros módulos usados por los desarrolladores de Fink, los cuales cualquiera puede ver, pero no son muy interesantes para la mayoría de los usuarios.</p>
  </section>
  <section>
    <title>Actualizando las Descripciones de los Paquetes</title>
    <p>Antes, esto era muy tedioso; pero en las versiones recientes de Fink es muy simple. Solo ejecuta este comando:
</p>
    <codeblock>fink selfupdate-cvs</codeblock>
    <p>Fink ejecutara todos los pasos necesarios automaticamente. Esto incluye conseguir las descripciones más recientes delos paquetes, actualizando los paquetes esenciales (entre ellos, el manejador de paquetes del Fink).
</p>
    <p>Si estas tras un firewall, consulta el <link url="/faq/usage-fink.php#proxy">FAQ 3.2</link>.
</p>
    <p>Despues de que se hayan actualizado las descripciones de los paquetes de esta manera, puedes actualizar los paquetes a sus últimas versiones. Esto se realiza ejecutando el comando:
</p>
    <codeblock>fink update-all</codeblock>
  </section>
  <section>
    <title>Actualizando el Manejador de Paquetes</title>
    <p>
<em>Nota:</em> A partir del 20 de Septiembre del 2001, ya no es necesario actualizar el manejador de paquetes independientemente; ahora es como cualquier paquete. Aún es posible actualizar directamente del CVS, aunque esto sólo es útil para la gente creando paquetes, no para el usuario promedio.  
</p>
    <p>El manejador de paquetes debe ser actualizado a través de un directorio separado y con el script<code>inject.pl</code> Este script pone las descripciones del paquete asi como los archivos tar para el fink y los archivos-bases en tu directorio Fink y entonces los construye.c</p>
    <p>Para ejecutar esto por primera vez, necesitaras un directorio temporal (llamado <code>tempdir</code> en el ejemplo) el cual esta vacío (o por lo menos que no tenga un subdirectorio llamado  'fink'). El procedimiento es como sigue:</p>
    <codeblock>cd tempdir
cvs -d:pserver:anonymous@fink.cvs.sourceforge.net:/cvsroot/fink login
cvs -z3 -d:pserver:anonymous@fink.cvs.sourceforge.net:/cvsroot/fink co fink
cd fink
./inject.pl</codeblock>
    <p>Este comando de login solicitará un password - presiona return y continua. El directorio temporal puede ser eliminado una vez que el proceso haya concluido, pero si no lo haces asá, la siguiente vez que actualices sera más fácil. El procedimiento entonces será:</p>
    <codeblock>cd tempdir/fink
cvs -z3 update -d
./inject.pl</codeblock>
  </section>
</article>

=== babayoshihiko/website/xml/cvsaccess/cvs.pt.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="pt" fsroot="../../">
<title>Configurando acesso via CVS para o Fink</title>
<shorttitle>Acesso via CVS</shorttitle>
<cvsid>$Id: cvs.pt.xml,v 1.2 2012/11/11 15:20:13 gecko2 Exp $</cvsid>

<preface>
  <p>O Fink é desenvolvido via CVS. Isto significa que você pode manter-se
  atualizado entre os lançamentos e sempre obter os arquivos mais recentes.
  Esta página informa como configurar uma instalação do Fink para fazer
  atualizações via CVS. As informações nesta página aplicam-se ao Fink 0.3.x e
  posteriores.</p>
</preface>


<section>
  <title>A estrutura do CVS do Fink</title>

  <p>O Fink possui vários módulos CVS. O módulo <code>dists</code>
  (<link url="http://fink.cvs.sourceforge.net/fink/">ViewCVS</link>) contém as
  descrições de pacotes e ajustes para o OS X 10.2 e posteriores. Há outros
  módulos usados pelos desenvolvedores do Fink que podem ser vistos por
  qualquer um. Todavia, esses módulos não são de interesse para a maior parte
  dos usuários.</p>
</section>

<section>
  <title>Atualizando as descrições de pacotes</title>

  <p>No passado, esse era um procedimento tedioso. Entretanto, nas versões
  atuais do Fink, tornou-se um procedimento bastante simples. Basta executar o
  comando:</p>
  <codeblock>fink selfupdate-cvs</codeblock>
  <p>O Fink executará automaticamente todos os passos para você. Isto inclui a
  obtenção do conjunto mais recente de descrições de pacotes e atualização de
  alguns pacotes bases essenciais, dentre os quais o gerenciador de pacotes
  Fink.</p>

  <p>Caso esteja atrás de um firewall, consulte a <link
  url="/faq/usage-fink.php#proxy">Pergunta frequente
  3.2</link>.</p>

  <p>Após haver atualizado suas descrições de pacotes desta forma, você pode
  querer atualizar seus pacotes para as últimas versões disponíveis. Você pode
  fazê-lo com o seguinte comando:</p>
  <codeblock>fink update-all</codeblock>
</section>

<section>
  <title>Atualizando o gerenciador de pacotes</title>

  <p><em>Observação:</em>Desde 20 de setembro de 2001, não é mais necessário
  atualizar o gerenciador de pacotes em separado; ele é tratado como qualquer
  outro pacote. Ainda é possível atualizá-lo diretamente via CVS apesar de que
  isto geralmente só é de interesse para as pessoas que criam pacotes e não os
  usuários comuns.</p>

  <p>O gerenciador de pacotes deve ser atualizado através de um diretório
  separado e o script <code>inject.pl</code>. Esse script coloca as descrições
  de pacotes e tarballs referentes ao fink e pacotes bases em uma árvore
  especial do Fink e os compila.</p>

  <p>Para o procedimento inicial, você precisa de um diretório temporário
  (denominado <code>tempdir</code> no exemplo) que esteja vazio (ou ao menos
  não contenha um subdiretório denominado 'fink'). O procedimento é como
  segue:</p>

  <codeblock>cd tempdir
cvs -d:pserver:anonymous@fink.cvs.sourceforge.net:/cvsroot/fink login
cvs -z3 -d:pserver:anonymous@fink.cvs.sourceforge.net:/cvsroot/fink co fink
cd fink
./inject.pl</codeblock>

  <p>O comando login solicitará uma senha - basta pressionar Return. Você pode
  remover o diretório temporário após esse procedimento mas, caso você o
  mantenha, a atualização será mais fácil na próxima vez, bastando digitar os
  seguintes comandos:</p>
  <codeblock>cd tempdir/fink
cvs -z3 update -d
./inject.pl</codeblock>
</section>

</article>

=== babayoshihiko/website/xml/cvsaccess/cvs.de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="de" fsroot="../../">
<title>CVS Zugang für Fink aufsetzen</title>
<shorttitle>Fink CVS Zugang</shorttitle>
<cvsid>$Id: cvs.de.xml,v 1.1 2015/02/19 15:21:03 k-m_schindler Exp $</cvsid>

<preface>
<p>
Fink wird über CVS entwickelt. Dies bedeutet, dass sie zwischen den
Releases aktuell bleiben und die jeweils neuesten Sachen bekommen können.
Diese Seite beschreibt, wie man eine existierende Installation von Fink
aufsetzt, damit man sie mittels CVS aktualisieren kann. Die Informationen
auf dieser Seite gelten für Fink 0.3.x und darüber.
</p>
</preface>

<section><title>Fink CVS Struktur</title>
<p>
Fink hat mehrere CVS-Module. Das Modul <code>dists</code> (<link
url="http://fink.cvs.sourceforge.net/fink/">ViewCVS</link>) enthält die
Paketbeschreibungen und die Korrekturen für OS X 10.2 und darüber. Es
gibt noch weitere Module, die von Fink-Entwicklern benutzt werden und von
jedem eingesehen werden könnnen, aber sie sind für die meisten Nutzer
uninteressant.
</p>
</section>

<section><title>Paketbeschreibungen aktualisieren</title>
<p>
In der Vergangenheit war dies eine recht umständliche Prozedur, aber in
der aktuellen Version von Fink ist es sehr einfach. Führen sie einfach
folgendes Kommando aus:
</p>
<codeblock>fink selfupdate-cvs</codeblock>
<p>
Fink wird automatisch alle notwendigen Schreitte für die Aktualisierung
ausführen. Dazu gehört das Empfangen der neuesten Paketbeschreibungen
und die Aktualisierung einiger essentieller Kern-Pakete (Darunter auch des
Fink Paket-Managers).
</p>
<p>
Sind sie hinter einer Firewall, lesen sie <link
url="/faq/usage-fink.php#proxy">FAQ 3.2</link>.
</p>
<p>
Nachdem die Paketbeschreibungen wie oben beschrieben aktualisiert sind,
werden sie normalerweise die installierten Pakete auf die neueste Version
aktualisieren wollen. Führen sie dazu folgendes Kommando aus:
</p>
<codeblock>fink update-all</codeblock>
</section>

<section><title>Den Paket-Manager aktualisieren</title>
<p>
<em>Notiz:</em> Ab dem 20. September 2001 ist es nicht mehr notwendig, den
Paket-Manager separat zu aktualisieren. Er wird wie alle anderen Paket
behandelt. Es ist aber immer noch möglich, ihn direkt aus CVS zu
aktualisieren. Dies ist aber auch nur dann interessant, wenn man Paket
erstellt, aber nicht als normaler Nutzer von Fink.
</p>
<p>
Den Paket-Manager muss man über ein separates Verzeichnis aktualisieren
und über das Skript <code>inject.pl</code>. Dieses Skript kopiert die
Paketbeschreibungen und die Tarballs für die Pakete Fink und die
Base-Files in ihren Baum und erstellt die Pakete.
</p>
<p>
Beim ersten Mal muss man ein temporäres Verzeichnis erstellen (im
Beispiel <code>tempdir</code> genannt), das leer ist, bzw. auf keinen Fall
ein Unterverzeichnis 'fink' enthält. Die gesamte Prozedur besteht aus
folgenden Kommandos:'
</p>
<codeblock>cd tempdir
cvs -d:pserver:anonymous@fink.cvs.sourceforge.net:/cvsroot/fink login
cvs -z3 -d:pserver:anonymous@fink.cvs.sourceforge.net:/cvsroot/fink co fink
cd fink
./inject.pl</codeblock>
<p>
Das login-Kommando fragt nach einem Passwort. Drücken sie einfach die
Return-Taste. Man kann dieses Verzeichnis nach der Aktualisierung
löschen, aber es ist auch ganz praktisch, es für die nächste
Aktualisierung auf zu heben. Die gesamte Prozedur besteht dann nur noch
aus diesen Kommandos:
</p>
<codeblock>cd tempdir/fink
cvs -z3 update -d
./inject.pl</codeblock>
</section>

</article>

=== babayoshihiko/website/xml/cvsaccess/cvs.fr.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="fr" fsroot="../../">
<title>Configuration de l'accès à Fink via CVS</title>
<shorttitle>Accès CVS à Fink</shorttitle>
<cvsid>$Id: cvs.fr.xml,v 1.4 2004/10/21 06:24:22 michga Exp $</cvsid>

<preface>
<p>
Fink est développé via CVS.
Cela vous permet de rester à jour entre deux versions et d'avoir toujours les paquets les plus récents.
Cette page vous explique comment configurer une installation Fink existante pour qu'elle puisse être mise à jour via CVS.
Les informations ci-dessous sont applicables à la version 0.3.x de Fink et aux versions ultérieures.
</p>
</preface>


<section><title>Structure CVS de Fink</title>
<p>Fink comporte plusieurs modules CVS. Le module <code>dists</code> (<link
url="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/fink/dists/">ViewCVS</link>)
contient les descriptions de paquets et les rustines pour OS X versions 10.2 et ultérieures. Il existe d'autres modules pour les développeurs de Fink. Vous pouvez les afficher, mais ils n'ont aucun intérêt pour la plupart des utilisateurs.</p>
</section>

<section><title>Mise à jour des descriptions de paquets</title>
<p>Auparavant, la procédure était compliquée ; mais, avec la version actuelle de Fink, elle s'est grandement simplifiée. Il faut suffit de lancer cette commande :
</p>
<codeblock>fink selfupdate-cvs</codeblock>
<p>Fink exécute alors automatiquement toutes les étapes nécessaires. Il récupère les descriptions de paquets les plus récentes et met à jour un certain nombre de paquets fondamentaux (dont le gestionnaire de paquets Fink).
</p>
<p>Si vous êtes derrière un mur pare-feu, consultez <link url="http://fink.sourceforge.net/faq/usage-fink.php#proxy">QFP 3.2</link>.
</p>
<p>Après avoir ainsi mis à jour les descriptions de paquets, vous pouvez mettre à jour les paquets. Pour ce faire, lancez la commande suivante :
</p>
<codeblock>fink update-all</codeblock>
</section>

<section><title>Mise à jour du gestionnaire de paquets</title>
<p>
<em>Note :</em> Depuis le 20 septembre 2001, il n'est plus utile d'effectuer une mise à jour spéciale pour le gestionnaire de paquets ; il est traité comme n'importe quel autre paquet.
Il est, cependant, toujours possible de le mettre à jour directement via CVS, bien que cela ne soit vraiment utile qu'aux personnes qui créent des paquets.
</p>

<p>Le gestionnaire de paquets doit être mis à jour dans un répertoire distinct à l'aide du script <code>inject.pl</code>. Ce script met dans votre arborescence Fink les descriptions de paquets et les archives tar de fink et des paquets fondamentaux, puis les compile.</p>
<p>La première fois, vous devez utiliser un répertoire temporaire (nommé <code>tempdir</code> par exemple) vide (ou qui ne contient pas lui-même un sous-répertoire 'fink'). Voici la procédure à suivre :</p>
<codeblock>cd tempdir
cvs -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink login
cvs -z3 -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink co fink
cd fink
./inject.pl</codeblock>
<p>La commande login vous demandera un mot de passe - contentez d'appuyer sur la touche retour chariot. Vous pouvez supprimer le répertoire temporaire à la fin de la procédure. Toutefois, si vous le conservez, les mises à jour suivantes en seront facilitées. La procédure sera alors :</p>
<codeblock>cd tempdir/fink
cvs -z3 update -d
./inject.pl</codeblock>
</section>

</article>

=== babayoshihiko/website/xml/fink-readme/readme.es.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="readme" lang="es">
<title>Fink ReadMe</title>
<shorttitle>ReadMe</shorttitle>
<cvsid>$Id: readme.es.xml,v 1.1 2004/11/15 15:31:45 zifra Exp $</cvsid>

<preface>
<p>
Fink es un sistema de gestión de paquetes que facilita el acceso completo al mundo Open Source a los usuarios de Darwin y Mac OS X.
</p>
<p>
Con la ayuda de dpkg, mantiene una jerarquía de directorios separados.
Descarga las versiones originales del código fuente, las modifica si es necesario ,las configura para Darwin y las compila e instala.
La información sobre los paquetes disponibles y las modificaciones necesarias (las descripciones del paquete -"package descriptions"-) se mantienen de forma separada pero se incluyen normalmente con las distribuciones.
El código fuente actual se puede descargar de Internet si es necesario.
</p>
<p>
Aunque Fink no se puede considerar "maduro", tiene asperezas y carece de algunas características, es utilizado con éxito por un gran número de personas.
Por favor, lee las instrucciones cuidadosamente y no te sorprendas si algo no funciona como sería lo esperado.
Disponemos de  buenas explicaciones para muchos problemas; visita la web si necesitas ayuda.
</p>
<p>
Fink es distribuido bajo los términos de la licencia GNU General Public License.
Revisa el documento COPYING para más detalles.
</p>
</preface>

<section name="req"><title>Requerimientos</title>
<p>
Necesitas:
</p>
<ul>
<li><p>
Un sistema con Mac OS X instalado, versión 10.0 o superior.
(Todavía existen algunos problemas relacionados con enlaces perdidos en la versión 10.1)
Darwin 1.3.1 también debería funcionar pero todavía no ha sido verificado.
Versiones anteriores  de ambos podrían <em>no</em> funcionar.
</p></li>
<li><p>
Herramientas de desarrollo.
Para Mac OS X, instala el paquete Developer.pkg del CD Developer
Tools CD.
Comprueba que las herramientas instaladas corresponden a tu versión del Mac OS X.
Para Darwin,  las herramientas deberían estar instaladas por defecto por el instalador.
</p></li>
<li><p>
Acceso a Internet.
Todo el código fuente puede descargarse de los diferentes espejos -mirror-.
</p></li>
<li><p>
Paciencia.
Compilar paquetes grandes lleva su tiempo.
Hablo de horas o incluso días.
</p></li>
</ul>
</section>

<section name="install"><title>Instalación</title>
<p>
El proceso de instalación se describe detalladamente en el documento INSTALL.
Por favor, léelo primero, el proceso no es trivial.
También describe el procedimiento de actualización.
</p>
</section>

<section name="usage"><title>Utilizando Fink</title>
<p>
El documento USAGE describe cómo colocar los "paths" y cómo instalar y remover paquetes.
Incluye también una lista completa de comandos disponibles.
</p>
</section>

<section name="questions"><title>Otras preguntas</title>
<p>
Si la documentación no responde todas tus preguntas, visita la web de Fink 
<link url="http://fink.sourceforge.net/">http://fink.sourceforge.net/</link>
y repasa la página de ayuda -Help page- :
<link url="http://fink.sourceforge.net/help/">http://fink.sourceforge.net/help/</link>.
Puede indicarte dónde encontrar documentación adicional y lugares de ayuda si fuera necesario,
</p>
<p>
Si deseas contribuir a Fink, la página de ayuda mencionada anteriormente también dispone de una lista de cosas que puedes hacer, como verificar y crear paquetes.
</p>
</section>

<section name="uptodate"><title>Mantenerse informado</title>
<p>
La web del proyecto se encuentra en
<link url="http://fink.sourceforge.net/">http://fink.sourceforge.net/</link>.
</p>
<p>
Para mantenerte informado de nuevas versiones, visita 
<link url="http://fink.sourceforge.net/lists/fink-announce.php">http://fink.sourceforge.net/lists/fink-announce.php</link>
y apúntate a la lista de correo fink-announce mailing list.
La lista es moderada y de tráfico bajo.
</p>
</section>

</article>

=== babayoshihiko/website/xml/fink-readme/readme.ja.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="readme" lang="ja">
<title>Fink ReadMe</title>
<shorttitle>ReadMe</shorttitle>
<cvsid>$Id: readme.ja.xml,v 1.4 2012/11/11 15:20:15 gecko2 Exp $</cvsid>

<preface>
<p>
Fink は Open Source ソフトウェアを Darwin と Mac OS X　で使えるようにすることを目的としたパッケージ管理システムです。
</p>
<p>
dpkg を使うことで、独立したディレクトリハイエラルキーを保ってるシステムです。
主な機能として、元となるソースリリースをダウンロード、必要に応じたパッチ当て、 Darwin 用の configure 、コンパイル、インストールを行います。
利用可能なパッケージと必要なパッチの情報 ("パッケージ詳細") は別々に管理され、通常この配布に含まれています。
実際のソースコードは必要に応じてインターネットからダウンロードされます。
</p>
<p>
Fink はまだ荒削りで機能不足なため「成熟」した状態にあるとは言えませんが、既に多くの人々に使われています。
使用方法をよく読み、たとえうまくいかなくても驚かないでください。
多くの問題は既に分析されていて、ウェブサイトに情報があります。
</p>
<p>
Fink は GNU General Public License の下で配布されています。
詳細は COPYING ファイルをご覧ください。
</p>
</preface>

<section name="req"><title>動作条件</title>
<p>
以下が必要です:
</p>
<ul>
<li><p>
インストール済み Mac OS X システム、バージョン 10.0 以降。
(10.1 にリンカ関連の問題が多少残っています)
Darwin 1.3.1 も動作すると思われますが、テストはされていません。
これより前のバージョンは<em>動作しません</em>。
</p></li>
<li><p>
開発ツール。
Mac OS X では Developer Tools CD から Developer.pkg パッケージをインストールして下さい。
このツールは Mac OS X バージョンに対応している必要があります。
Darwin では、デフォルトインストールでツールが揃っているはずです。
</p></li>
<li><p>
インターネットへの接続。
すべてのソースコードはミラーサイトからダウンロードされます。
</p></li>
<li><p>
忍耐。
コンパイル、特に大きなパッケージには時間がかかります。
数時間から数日かかることもあります。
</p></li>
</ul>
</section>

<section name="install"><title>インストール</title>
<p>
インストール方法は INSTALL ファイルに書かれています。
インストール方法は簡単ではないので、これを最初にお読みください。。
また、アップグレード方法も書かれています。
</p>
</section>

<section name="usage"><title>Fink の使用方法</title>
<p>
USAGE ファイルにパスの通し方やパッケージのインストールや削除方法が書かれています。
また、コマンド一覧も書かれています。
</p>
</section>

<section name="questions"><title>質問?</title>
<p>
If the documentation included here doesn't answer your question,
stroll over to the Fink website at
もしここにあるドキュメントで質問に答えていない場合、 Fink ウェブサイト
<link url="/">/</link>
に来て、ヘルプページを参照してください:
<link url="/help/">/help/</link> 。
ここにほかのドキュメントやサポートの得られる場所についての情報が書かれています。
</p>
<p>
Fink に貢献をしたい場合、上記のヘルプページに、テストやパッケージ作成など、現在募集している内容一覧があります。
</p>
</section>

<section name="uptodate"><title>告知</title>
<p>
当プロジェクトのウェブサイトは
<link url="/">/</link>
です。
</p>
<p>
新しいリリースの情報は、
<link url="/lists/fink-announce.php">/lists/fink-announce.php</link>
から fink-announce メーリングリストを購読してください。
このリストは受信専用で、トラフィック量は小さいです。
</p>
</section>

</article>
