=== babayoshihiko/website/xml/finkdoc.dtd
<!-- Root elements -->
<!ELEMENT article ( title, shorttitle, cvsid, preface?, section+ ) >
<!ATTLIST article filename NMTOKEN #REQUIRED >

<!ELEMENT document ( title, shorttitle, cvsid, preface?, chapter+ ) >
<!ATTLIST document filename NMTOKEN #REQUIRED >


<!-- Structure -->
<!ELEMENT chapter ( title, shorttitle, preface?, section+ )* >
<!ATTLIST chapter filename NMTOKEN #REQUIRED >

<!ELEMENT title ( #PCDATA ) >
<!ELEMENT shorttitle ( #PCDATA ) >
<!ELEMENT cvsid ( #PCDATA ) >
<!ELEMENT preface ( p+ ) >

<!ELEMENT section (title?, ( codeblock | itemtable | ol | p | ul )*) >
<!ATTLIST section name NMTOKEN #IMPLIED >


<!-- Block elements -->
<!ELEMENT codeblock ( #PCDATA | em )* >
<!ELEMENT p ( #PCDATA | code | codeblock | em | link | tt | xref )* >


<!-- Inline -->
<!ELEMENT code ( #PCDATA | em )* >
<!ELEMENT em ( #PCDATA ) >
<!ELEMENT tt ( #PCDATA ) >


<!-- Links -->
<!ELEMENT link ( #PCDATA ) >
<!ATTLIST link url CDATA #REQUIRED >

<!ELEMENT xref ( #PCDATA ) >
<!ATTLIST xref chapter NMTOKEN #IMPLIED >
<!ATTLIST xref section NMTOKEN #IMPLIED >


<!-- Lists -->
<!ELEMENT ol ( li+ ) >
<!ELEMENT ul ( li+ ) >
<!ELEMENT li ( #PCDATA | code | codeblock | em | link | p )* >

<!ELEMENT itemtable ( item+ ) >
<!ATTLIST itemtable labeld CDATA "Value" >
<!ATTLIST itemtable labelt CDATA "Field" >

<!ELEMENT item ( itemt, itemd ) >
<!ELEMENT itemt ( #PCDATA | code | em )* >
<!ELEMENT itemd ( codeblock | p | ul )* >

=== babayoshihiko/website/xml/fink-readme/readme.fr.xml
<?xml version = '1.0' encoding = 'UTF-8' ?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">
<article filename="readme" lang="fr" >
  <title>Fink Lisez-moi</title>
  <shorttitle>Lisez-moi</shorttitle>
  <cvsid>$Id: readme.fr.xml,v 1.5 2006/09/16 23:17:53 dmrrsn Exp $</cvsid>
  <preface>
    <p>
Voici Fink, un système de gestion de paquets qui a pour but d'ouvrir toutes grandes les portes du monde des logiciels Open Source à  Darwin et Mac OS X.
</p>
    <p>
Grâce à  dpkg, il maintient une hiérarchie de répertoires dédiés.
Il récupère les versions sources originales, leur applique éventuellement des rustines, les configure pour Darwin, les compile et les installe.
Les informations concernant les paquets disponibles et les rustines nécessaires (les &quot;descriptions de paquets&quot;) sont gérées séparément, bien qu'elles soient généralement incluses dans cette distribution.
Le code source est, quant à  lui, récupéré sur Internet, si nécessaire.
</p>
    <p>
Bien que Fink ne puisse être considéré comme &quot;mature&quot;, qu'il comporte quelques aspects non polis et que certaines fonctionnalités lui fassent défaut, un grand nombre de personnes l'utilisent sans problèmes.
Lisez soigneusement les instructions et ne soyez pas surpris si quelque chose ne fonctionne pas exactement comme prévu.
Il existe des explications détaillées pour la plupart des dysfonctionnements ; voyez le site web en cas de besoin.
</p>
    <p>
Fink est distribué sous licence Publique Générale GNU. 
Voir le fichier COPYING pour plus d'informations.
</p>
  </preface>
  <section name="req" >
    <title>Configuration requise</title>
    <p>
Vous devez disposer :
</p>
    <ul>
      <li>
        <p>
D'un système Mac OS X installé, version 10.0 ou postérieure (il peut y avoir quelques problèmes relatifs à  l'édition de liens avec 10.1).
Darwin 1.3.1 devrait aussi fonctionner, mais il n'a pas été testé.
Il est <em>impossible</em> de faire fonctionner Fink sous des versions antérieures de l'un ou l'autre de ces systèmes.
</p>
      </li>
      <li>
        <p>
Des outils de développement.
Sous Mac OS X, installez le paquet Developer.pkg à partir du CD Developer
Tools.
Vérifiez que la version des outils de développement que vous installez correspond à  celle de Mac OS X.
Sous Darwin, les outils de développement sont inclus dans l'installation par défaut.</p>
      </li>
      <li>
        <p>
D'un accès Internet.
Tous les sources sont chargés à partir des sites miroirs.
</p>
      </li>
      <li>
        <p>
De la patience.
Compiler plusieurs gros paquets prend du temps.
Il peut s'agir de plusieurs heures, voire de plusieurs jours.
</p>
      </li>
    </ul>
  </section>
  <section name="install" >
    <title>Installation</title>
    <p>
Le processus d'installation est décrit en détail dans le fichier INSTALL.
Veuillez le lire avant de faire quoi que ce soit, ce processus n'est pas trivial.
Le fichier décrit aussi la procédure de mise à  jour.
</p>
  </section>
  <section name="usage" >
    <title>Utilisation de Fink</title>
    <p>
Le fichier USAGE explique comment définir les chemins nécessaires et comment installer et désinstaller des paquets.
Il comprend aussi une liste complète des commandes disponibles.
</p>
  </section>
  <section name="questions" >
    <title>Autres questions</title>
    <p>
Si la documentation incluse ne répond pas à  vos questions, allez sur le site web de Fink <link url="http://www.finkproject.org/" >http://www.finkproject.org/</link> et consultez la page Aide :
<link url="http://www.finkproject.org/help/" >http://www.finkproject.org/help/</link>.
Elle vous conduira au reste de la documentation disponible et à d'autres sources de support, le cas échéant.
</p>
    <p>
Si vous voulez apporter votre contribution à Fink, la page Aide mentionnée ci-dessus contient également une liste de tâches à réaliser, tels les tests et la création de paquets.
</p>
  </section>
  <section name="uptodate" >
    <title>Dernières nouvelles</title>
    <p>
La page du projet se trouve sur <link url="http://www.finkproject.org/" >http://www.finkproject.org/</link>.
</p>
    <p>
Pour vous tenir informé des dernières versions, allez à <link url="http://www.finkproject.org/lists/fink-announce.php" >http://www.finkproject.org/lists/fink-announce.php</link>
et abonnez-vous à la liste de diffusion fink-announce. 
La liste est modérée et son trafic est très faible.
</p>
  </section>
</article>

=== babayoshihiko/website/xml/cvsaccess/cvs.ja.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="en" fsroot="../../">
<title>Fink CVS アクセスを設定</title>
<shorttitle>Fink CVS アクセス</shorttitle>
<cvsid>$Id: cvs.ja.xml,v 1.1 2009/10/17 05:34:29 babayoshihiko Exp $</cvsid>

<preface>
<p>
Fink は CVS を用いて開発されています。 すなわち、リリース前にも、つねに最新の状態でいることができます。 このページでは、すでに Fink をインストールしている方を対象に、CVS での更新方法をお伝えいたします。 ここの情報は、 Fink 0.3.x 以降で有効です。
</p>
</preface>


<section><title>Fink CVS の構造</title>
<p>
Fink には、いくつかの CVS モジュールがあります。
<code>dists</code> (<link
url="http://fink.cvs.sourceforge.net/fink/">ViewCVS</link>)
モジュールには、OS X 10.2 以降のパッケージ記述ファイルとパッチが格納されています。
この他にも Fink 開発者によって使われているモジュールがあり、
誰でも見ることができますが、
おそらくほとんどのユーザーには関心がないことでしょう。
</p>
</section>

<section><title>パッケージ記述の更新</title>
<p>
以前は、これはちょっと手間のかかることでした。
しかし、現在の Fink では、とてもシンプルです。
以下のコマンドを実行してください。
</p>
<codeblock>fink selfupdate-cvs</codeblock>
<p>
あとは Fink が、必要なステップを自動的に行います。
これにより、最新のパッケージ記述の取得と必須コアパッケージ (Fink パッケージマネージャーを含む) の更新が行われます。
</p>
<p>
ファイアーウォールの内側にいる場合、
<link url="http://www.finkproject.org/faq/usage-fink.php#proxy">FAQ 3.2</link>
をご参考にしてください。
</p>
<p>
この方法でパッケージ記述を更新し、
インストール済みのパッケージを最新バージョンに更新したい場合、
以下のコマンドで行うことができます。
</p>
<codeblock>fink update-all</codeblock>
</section>

<section><title>パッケージマネージャーの更新</title>
<p>
<em>注記:</em> 2001年9月20日より、
パッケージマネージャーを個別に更新する必要はなくなりました。
他のパッケージと全く同様に行うことができます。
今でも CVS から直接更新することは可能ですが、
これはパッケージ制作者のためのもので、
一般ユーザーにはあまり関係ないことでしょう。
</p>

<p>The package manager must be updated through a separate directory
and the <code>inject.pl</code> script. That script puts package
descriptions and tarballs for the fink and base-files packages in your
Fink tree and builds them.
パッケージマネージャーは、独立したディレクトリを通して、
 <code>inject.pl</code> スクリプトで更新しなければなりません。
</p>
<p>
初めての場合、仮ディレクトリ（ここでは <code>tempdir</code> とする）が必要です。
これは空でなくてはいけません (あるいは少なくとも fink という名のサブディレクトリがあってはいけない)。
これは、その後、このようになります。
</p>
<codeblock>cd tempdir
cvs -d:pserver:anonymous@fink.cvs.sourceforge.net:/cvsroot/fink login
cvs -z3 -d:pserver:anonymous@fink.cvs.sourceforge.net:/cvsroot/fink co fink
cd fink
./inject.pl</codeblock>
<p>
ログインコマンドは、パスワードを尋ねてきます。
何も入力せずリターンキーを押してください。
この語、仮ディレクトリは削除してもかまいません。
ただし、残しておくと次回から更新が容易になります。
次回からは、
</p>
<codeblock>cd tempdir/fink
cvs -z3 update -d
./inject.pl</codeblock>
</section>

</article>

=== babayoshihiko/website/xml/fink-readme/readme.en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="readme" lang="en">
<title>Fink ReadMe</title>
<shorttitle>ReadMe</shorttitle>
<cvsid>$Id: readme.en.xml,v 1.6 2013/03/30 00:03:45 alexkhansen Exp $</cvsid>

<preface>
<p>
This is Fink, a package management system that aims to bring the full
world of Open Source software to Darwin and Mac OS X.
</p>
<p>
With the help of dpkg, it maintains a separate directory hierarchy.
It downloads original source releases, patches them if necessary,
configures them for Darwin and compiles and installs them.
The information about available packages and the necessary patches
(the "package descriptions") are maintained separately, but are
usually included with this distribution.
The actual source code is downloaded from the Internet as necessary.
</p>
<p>
Although Fink cannot be considered "mature" and it has some rough
edges and lacking features, it is successfully used by a large number
of people.
Please read the instructions carefully and don't be surprised if
something doesn't work as expected.
There are good explanations for most failures; check the website if
you need help.
</p>
<p>
Fink is released under the terms of the GNU General Public License.
See the file COPYING for details.
</p>
</preface>

<section name="req"><title>Requirements</title>
<p>
You need:
</p>
<ul>
<li><p>
An installed Mac OS X system, version 10.5 or later. 
Earlier versions will <em>not</em> work with fink-&fink_tool_version;.
</p></li>
<li><p>
Development tools.
On OS 10.6 and earlier, install the Developer.pkg package from the Developer Tools CD. 
If on 10.7 or later, download Xcode from the Mac App Store, and then install the "Command Line Tools for Xcode" from Xcode's preferences.
Make sure that the tools you install match your Mac OS X version. 
</p></li>
<li><p>
Internet access.
All source code is downloaded from mirror sites.
</p></li>
<li><p>
Patience.
Compiling several big packages takes time.
I'm talking hours or even days here.
</p></li>
</ul>
</section>

<section name="install"><title>Installation</title>
<p>
The installation process is described in detail in the file
INSTALL.
Please read it first, the process is non-trivial.
It also describes the upgrade procedure.
</p>
</section>

<section name="usage"><title>Using Fink</title>
<p>
The file USAGE describes how to set your paths and how to install and
remove packages.
It also has a complete list of available commands.
</p>
</section>

<section name="questions"><title>Further Questions?</title>
<p>
If the documentation included here doesn't answer your question,
stroll over to the Fink website at
<link url="/">/</link>
and check out the Help page there:
<link url="/help/">/help/</link>.
It will point you at the other documentation that is available and
sources for support if you need it.
</p>
<p>
If you'd like to contribute to Fink, the Help page mentioned above
also has a list of things you can do, like testing or creating
packages.
</p>
</section>

<section name="uptodate"><title>Staying Informed</title>
<p>
The project's website is at 
<link url="/">/</link>.
</p>
<p>
To be informed of new releases, go to
<link url="/lists/fink-announce.php">http://www.fink.sourceforge.net/lists/fink-announce.php</link>
and subscribe to the fink-announce mailing list.
The list is moderated and low-traffic.
</p>
</section>

</article>

=== babayoshihiko/website/xml/doc/doc.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index">
<title>Fink - Documentation</title>
<shorttitle></shorttitle>
<cvsid>$Id: doc.xml,v 1.1 2003/04/14 00:13:18 dmrrsn Exp $</cvsid>

<preface>
<p>
This is a collection of various documents written for Fink.
Some of the documents may also be useful to people who use Mac OS X
or Darwin without Fink and want to learn about porting Unix software.
</p>
</preface>

<section name="userdoc"><title>User Documentation</title>

<p>
The current user documentation for Fink:
</p>
<ul>
<li><link url="users-guide/index.php">Fink User's Guide</link> -
this covers installing Fink itself, installing packages, and upgrading
to a new Fink release. It contains instructions for both the source
and the binary release.
<em>Work in Progress!</em></li>
<li><link url="x11/index.php">Running X11 on Darwin and Mac OS X</link> -
covers concepts, installation and launching (also intended for Darwin
and Mac OS X users in general)</li>
</ul>

<p>
A bunch of documents that are more complete, but slightly outdated and
no longer maintained:
</p>
<ul>
<li><link url="bundled/install.php">Installation and Upgrading</link> - how
to install Fink or upgrade to a new version</li>
<li><link url="bundled/usage.php">Usage</link> - how to use Fink
and the installed software</li>
<li><link url="bundled/readme.php">Fink ReadMe</link> - the ReadMe for the
source distribution</li>
<li><link url="cvsaccess/index.php">CVS Access</link> - how to access the
Fink CVS repository to get the latest source packages between
releases</li>
</ul>

</section>

<section name="developerdoc"><title>Developer Documentation</title>

<ul>
<li><link url="http://fink.sourceforge.net/doc/UsingFink.pdf">Using Fink: A Developer's How To</link> (2MB pdf
file) - slides from a presentation at the <link
url="http://conferences.oreillynet.com/macosx2002/"
>O'Reilly Mac OS X Conference</link> (also available as a
<link url="http://conferences.oreillynet.com/presentations/macosx02/morrison_david.ppt">PowerPoint file</link>) </li>
<li><link url="porting/index.php">Porting Tips</link> - notes for porting
Unix applications to Darwin</li>
<li><link url="packaging/index.php">Packaging Manual</link> - how to create and
maintain Fink packages</li>
</ul>

</section>
</article>

=== babayoshihiko/website/xml/fink-readme/readme.ru.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">
<article filename="readme" lang="ru">
    <title>Ознакомительный файл Fink</title>
    <shorttitle>Ознакомительный файл</shorttitle>
    <cvsid>$Id: readme.ru.xml,v 1.3 2012/11/11 15:20:15 gecko2 Exp $</cvsid>
    <preface>
        <p> Система управления пакетами Fink предназначена для переноса
            всего мира ПО с открытым исходным кодом в Darwin и Mac OS X.</p>
        <p> При помощи dpkg она поддерживает отдельную иерархию каталогов.
            Fink скачивает версии оригинального исходного кода, при необходимости делает в них патчи,
            конфигурирует эти версии для Darwin, затем компилирует и инсталлирует.
            Информация об имеющихся пакетах и необходимых патчах
            ("описание пакетов") поддерживается отдельно, но обычно входит
            в состав дистрибуции. Реальный исходный код скачивается
            по мере необходимости из Internet.</p>
        <p> Хотя Fink не может считаться "зрелой" системой и имеет определенные жесткие ограничения
            и недостающие параметры, она успешно используется большим количеством людей.
            Просим внимательно прочитать инструкции и не удивляться, если
            что-то будет работать не так, как вы ожидали. Для большинства
            сбоев существует обоснованное объяснение; если потребуется помощь, посетите наш веб-сайт.</p>
        <p> Fink выпускается на условиях Общей публичной лицензии GNU.
            См. файл COPYING для получения более подробной информации.</p>
    </preface>
    <section name="req">
        <title>Требования</title>
        <p> Вам необходимо иметь следующее:</p>
        <ul>
            <li>
                <p> Инсталлированная система Mac OS X, версия 10.0 или более поздняя. (Иногда
                    все еще могут возникать проблемы с 10.1 из-за компоновщика.)
                    Darwin 1.3.1 также должна работать, но это не проверено.
                    Более ранние версии обеих систем <em>не</em> будут работать.</p>
            </li>
            <li>
                <p> Компакт-диск инструментов разработки. Надо инсталлировать пакет Developer.pkg в Mac OS X с компакт-диска Developer Tools.
                    Надо убедиться, что инсталлируемые вами инструменты соответствуют версии вашей Mac OS X. В Darwin
                    инструменты уже есть по умолчанию после инсталляции. </p>
            </li>
            <li>
                <p> Доступ в Internet. Весь исходный код скачивается с зеркальных сайтов.</p>
            </li>
            <li>
                <p> Терпение. Компиляция нескольких больших пакетов занимает время. Я в это время
                    болтаю часами и даже днями.</p>
            </li>
        </ul>
    </section>
    <section name="install">
        <title>Инсталляция</title>
        <p>Процесс инсталляции подробно описан  в файле "Инсталляция".
            Просим сначала ознакомиться с текстом, т.к. процесс необычен. Здесь же описывается процедура
            обновления.</p>
    </section>
    <section name="usage">
        <title>Использование Fink</title>
        <p> Файл "Использование" описывает, как настраивать маршруты, инсталлировать и
            удалять пакеты. Кроме того, он включает полный список имеющихся команд.</p>
    </section>
    <section name="questions">
        <title>Другие вопросы?</title>
        <p> Если в предлагаемой документации нет ответа на ваш вопрос,
            перейдите с веб-сайта Fink на <link
            url="/">/</link>
            и посмотрите там страницу Help:<link
            url="/help/">/help/</link>.
            На ней вы найдете сведения обо всей другой имеющейся документации и источниках
            необходимой вам поддержки.</p>
        <p> Если вы хотите внести свой вклад в развитие Fink,  вышеуказанная страница Help также
            содержит список того, что вы можете сделать - например, тестирование или создание пакетов.</p>
    </section>
    <section name="uptodate">
        <title>Регулярное получение информации</title>
        <p> Адрес веб-сайта проекта: <link url="/">/</link>.</p>
        <p> Для регулярного получения информации о новых версиях можно подписаться на список рассылки fink-announce на <link
            url="/lists/fink-announce.php">/lists/fink-announce.php</link>.
            Это умеренный список с низким уровнем трафика.
            </p>
    </section>
</article>

=== babayoshihiko/website/xml/cvsaccess/cvs.zh.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index" lang="zh" fsroot="../../">
<title>设置 Fink CVS 访问</title>
<shorttitle>Fink CVS 访问</shorttitle>
<cvsid>$Id: cvs.zh.xml,v 1.1 2004/03/16 04:03:28 jeff_yecn Exp $</cvsid>

<preface>
<p>
Fink 被开发为支持 CVS。
这意味着你可以在两个发布版之间都可以一直保持使用当前最新的版本，总是可以获得最新的功能。
本页介绍如何配置一个已安装的 Fink 通过 CVS 进行更新。
本页的资讯适用于 Fink 0.3.x 或更新的版本。
</p>
</preface>


<section><title>Fink CVS 结构</title>
<p>Fink 有几个 CVS 模块。模块 <code>dists</code>（<link
url="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/fink/dists/">《查看 CVS》</link>）包含软件包描述和对 OS X 10.2 及更新版本的补丁。
这里面还有被 Fink 开发者使用的其它模块，其它人可以查看，但多数用户都不会对他们感兴趣。</p>
</section>

<section><title>更新软件包描述</title>
<p>过去，这是一个比较冗长的过程，但在现在的 Fink 版本中，这是一个非常简单的过程。
只需要运行这个命令：
</p>
<codeblock>fink selfupdate-cvs</codeblock>
<p>Fink 会为你执行必需的步骤。
这包括获取最新一套软件包描述文件，以及更新一些重要的核心软件包（中间包括 Fink 软件包管理器）。
</p>
<p>如果你在防火墙之后，参考<link url="http://fink.sourceforge.net/faq/usage-fink.php#proxy">《常见疑问 3.2》</link>。
</p>
<p>在你这样更新了你的软件包描述之后，你可以接着更新你的软件包到最新的版本。这可以使用下面的命令：
</p>
<codeblock>fink update-all</codeblock>
</section>

<section><title>更新软件包管理器</title>
<p>
<em>注意：</em>从 2001 年 9 月 20 日开始，不再需要单独更新软件包管理器了它已经被单独看作普通软件包中的一个。
它仍然可以直接从 CVS 进行更新，虽然通常只用软件包的开发者才会对此感兴趣，普通用户不会关心它。
</p>

<p>软件包管理器需要通过一个单独的目录以及一个 <code>inject.pl</code> 脚本进行更新。这个脚本把软件包描述文件和 Fink 程序的压缩档以及基本文件软件包到你的 Fink 目录树中并构建它们。</p>
<p>第一的过程中，你需要创建一个空的（或至少不包括称为 'fink' 的子目录）临时目录（比如称为 <code>tempdir</code>）。
操作过程大致如下：</p>
<codeblock>cd tempdir
cvs -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink login
cvs -z3 -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink co fink
cd fink
./inject.pl</codeblock>
<p>登录命令会询问密码──只需要按回车就好了。
再此过程以后你可以删除临时目录，但不过保留它们呢，那么下次的更新会简单一些。
接着的步骤是：</p>
<codeblock>cd tempdir/fink
cvs -z3 update -d
./inject.pl</codeblock>
</section>

</article>

=== babayoshihiko/website/xml/cvsaccess/cvs.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">

<article filename="index">
<title>Setting up Fink CVS Access</title>
<shorttitle>Fink CVS Access</shorttitle>
<cvsid>$Id: cvs.xml,v 1.8 2002/04/17 17:52:43 fingolfin Exp $</cvsid>

<preface>
<p>
Fink is developed via CVS.
This means that you can stay up to date between releases and always
get the newest stuff.
This page tells you how to set up an existing Fink installation for
updating via CVS.
The information on this page applies to Fink 0.3.x and later.
</p>
</preface>


<section><title>Fink CVS Structure</title>
<p>Fink has several CVS modules. The module <code>packages</code> (<link
url="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/fink/packages/">ViewCVS</link>)
contains the package descriptions and patches. There are other modules
used by Fink developers, which anyone is free to view, but which are
not interesting for most.</p>
</section>

<section><title>Updating the Package Descriptions</title>
<p>In the past this was a bit tedious procedure; but in the current Fink
versions, this is a very simple procedure. Just issue this command:
</p>
<codeblock>fink selfupdate-cvs</codeblock>
<p>Fink will perform all necessary steps automatically for you. This
includes retrieving the latest set of Package Descriptions, and updating
a few essential core packages (among them the Fink package manager).
</p>
<p>Note that this command currently doesn't work if you are behind a
firewall (this is a limitation in CVS, not in Fink). We are working
on a solution to tunnel through HTTP firewalls (by enhancing
cvs to support these), but no release date has been set for this.
</p>
<p>After you have updated your Package Descriptions this ways, you may
want to update your packages to the latest available versions. You can
do so by with the following command:
</p>
<codeblock>fink update-all</codeblock>
</section>

<section><title>Updating the Package Manager</title>
<p>
<em>Note:</em> As of September 20 it is no longer necessary to update
the package manager separately; it is treated like any other package.
It's still possible to update it directly from CVS, though this is
usually only interesting for people creating packages, not the avarage
user.
</p>

<p>The package manager must be updated through a separate directory
and the <code>inject.pl</code> script. That script puts package
descriptions and tarballs for the fink and base-files packages in your
Fink tree and builds them.</p>
<p>For the first time procedure, you need a temporary directory
(called <code>tempdir</code> in the example) which is empty (or at least
doesn't contain a subdirectory named 'fink'). The procedure goes like
this:</p>
<codeblock>cd tempdir
cvs -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink login
cvs -z3 -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink co fink
cd fink
./inject.pl</codeblock>
<p>The login command will ask for a password - just press return. You
could delete the temporary directory after the procedure, but if you
leave it around, updating is easier the next time. The procedure is
then:</p>
<codeblock>cd tempdir/fink
cvs -z3 update -d
./inject.pl</codeblock>
</section>

</article>

=== babayoshihiko/website/xml/cvsaccess/cvs.ru.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE article SYSTEM "../finkdoc.dtd">
<article filename="index" lang="ru" fsroot="../../">
    <title>Настройка доступа к Fink через CVS</title>
    <shorttitle>Доступ к Fink через CVS</shorttitle>
    <cvsid>$Id: cvs.ru.xml,v 1.2 2006/02/28 02:44:45 alexkhansen Exp $</cvsid>
    <preface>
        <p> Fink разработан через посредство CVS. Это значит, что вы можете быть в курсе 
         последних разработок между выпусками версий и всегда получать новейший материал. Данная страница рассказывает о том, 
           как можно произвести настройку имеющейся инсталляции Fink для обновления через 
            CVS. Информация на данной странице относится к Fink 0.3.x и более поздним версиям.</p>
    </preface>
    <section>
        <title>Структура CVS Fink </title>
        <p>Fink имеет несколько модулей CVS. Модуль <code>dists</code> (<link
            url="http://cvs.sourceforge.net/viewcvs.py/fink">ViewCVS</link>)
            содержит описание пакетов и патчи для OS X 10.2 и более поздних версий. Есть другие модули, используемые разработчиками Fink,  
            обзор которых доступен всем, но они не представляют интереса для большинства пользователей.</p>
    </section>
    <section>
        <title>Обновление описания пакетов</title>
        <p>Раньше это была довольно нудная процедура, но в текущих версиях Fink
            это очень просто. Просто дайте следующую команду:</p>
        <codeblock>fink selfupdate-cvs</codeblock>
        <p>Fink автоматически выполнит все необходимые вам действия, в том числе  
            найдет последний комплект описания пакетов и обновит несколько основных базовых пакетов 
            (среди них менеджер пакетов Fink).</p>
        <p>Если вы находитесь за брандмауэром, см. <link
                url="http://fink.sourceforge.net/faq/usage-fink.php#proxy">Ч.З.В. 3.2</link>.</p>
        <p>После обновления своего описания пакетов указанным образом у вас 
            может появиться желание обновить свои пакеты до последних возможных версий. 
            Это можно сделать при помощи следующй команды:</p>
        <codeblock>fink update-all</codeblock>
    </section>
    <section>
        <title>Обновление менеджера пакетов</title>
        <p>
            <em>Примечание:</em>С 20 сентября 2001 н. больше нет необходимости 
            обновлять менеджер пакетов отдельно; с ним обращаются, как с любым другим 
            пакетом. Все еще возможно обновлять его непосредственно из CVS, хотя
            это обычно интересует тех, кто создает пакеты, а не средних
            пользователей.</p>
        <p>Менеджер пакетов должен обновляться через отдельный каталог и
            скрипт <code>inject.pl</code>. Данный скрипт помещает описание 
            пакетов и тарболы для пакетов fink и базовых файлов 
            на вашем дереве Fink и осуществляет их построение.</p>
        <p>При выполнении первоначальной процедуры вам нужен временный каталог (в примере называемый 
            <code>tempdir</code>), который должен быть пустым (или по крайней мере не должен содержать
            подкаталог под именем 'fink'). Порядок действий 
            следующий:</p>
        <codeblock>cd tempdir cvs
            -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink login cvs -z3
            -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/fink co fink cd
            fink ./inject.pl</codeblock>
        <p>Команда login запросит пароль - просто нажмите return. Вы
            можете удалить временный каталог после данной процедуры, но если
            его оставить, будет легче произвести обновление в следующий раз. Тогда порядок действий таков:</p>
        <codeblock>cd tempdir/fink cvs -z3 update -d ./inject.pl</codeblock>
    </section>
</article>
